notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - oicr:S9k4EowgQv9AnbCfEZHSzCsg

sudo: required
services:
- docker

addons:
  postgresql: "9.4"

cache:
  directories:
  - $HOME/.m2

language: java
jdk:
- oraclejdk8

install: cd tooltester && mvn -B clean install -DskipITs=false cobertura:cobertura coveralls:report


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
