SERVER-URL: <ENTER SERVER URL HERE>
TOKEN: <ENTER DOCKSTORE TOKEN HERE>
AWS-AUTHORIZATION: <ENTER AWS PROFILE NAME HERE>
WDL-WES-URL: <ENTER URL RETRIEVED FROM RUNNING 'agc context describe' on the WDL context HERE>ga4gh/wes/v1
CWL-WES-URL:  <ENTER URL RETRIEVED FROM RUNNING 'agc context describe' on the CWL context HERE>ga4gh/wes/v1
WDL-ECS-CLUSTER: <ENTER ECS Cluster name for WDL context HERE>
CWL-ECS-CLUSTER: <ENTER ECS Cluster name for CWL context HERE>
