version: 2.1
parameters:
  java-tag:
    type: string
    default: "17.0.3"
orbs:
  build-tools: circleci/build-tools@2.7.0
executors:
  unit_tests_executor:
    docker: # run the steps with Docker
      - image: cimg/openjdk:<< pipeline.parameters.java-tag >>

  machine_integration_test_exec:
    machine: # run the steps with Ubuntu VM
      image: ubuntu-2204:2022.10.1
    environment:
      PGHOST: 127.0.0.1
    resource_class: medium

common_filters: &common_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore:
        - gh-pages

workflows:
  version: 2
  everything:
    jobs:
      - build-all:
          <<: *common_filters
      - metrics-aggregator-tests:
          <<: *common_filters
          requires:
            - build-all
      - tooltester-tests:
          <<: *common_filters
          requires:
            - build-all
      - toolbackup-tests:
          <<: *common_filters
          requires:
            - build-all
      - sonar-cloud:
          <<: *common_filters
          requires:
            - metrics-aggregator-tests
            - tooltester-tests
            - toolbackup-tests
          context: sonarcloud

jobs:
  metrics-aggregator-tests:
    executor: machine_integration_test_exec
    parallelism: 1
    environment:
      DIRECTORY: metricsaggregator
      MAVEN_GOAL: verify
    steps:
      - get_workspace_and_dependencies
      - setup_machine
      - setup_for_tests
      - setup_for_postgres
      - wait_for_elastic_search
      - run_tests
      - save_test_results
      - send_coverage
  tooltester-tests:
    docker: # run the steps with Docker
      - image: cimg/openjdk:<< pipeline.parameters.java-tag >>
    parallelism: 1
    environment:
      DIRECTORY: tooltester
      MAVEN_GOAL: verify
    steps:
      - get_workspace_and_dependencies
      - setup_for_tests
      - run_tests
      - save_test_results
      - send_coverage
  toolbackup-tests:
    executor: machine_integration_test_exec
    parallelism: 1
    environment:
      DIRECTORY: toolbackup
      MAVEN_GOAL: verify
    steps:
      - get_workspace_and_dependencies
      - setup_machine
      - setup_for_tests
      - run_tests
      - save_test_results
      - send_coverage
  sonar-cloud:
    docker: # run the steps with Docker
      - image: cimg/openjdk:<< pipeline.parameters.java-tag >>
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific licenses file checksum
            # when this file is changed, this key will fail
            - dockstore-support-java-{{ checksum "THIRD-PARTY-LICENSES.txt" }}
            # Find the most recent cache used from any branch
            - dockstore-support-java-
      - run:
          name: build
          command: ./mvnw clean install -DskipTests
      - run:
          name: SonarCloud scan - coverage
          command: ./mvnw -Dsonar.coverage.jacoco.xmlReportPaths=../coverage/* sonar:sonar

  build-all:
    docker: # run the steps with Docker
      - image: cimg/openjdk:<< pipeline.parameters.java-tag >>
        environment:
          # Java can read cgroup. Sadly the cgroup in
          # CircleCI is wrong. Have to manually set. Nothing to do with surefire
          # plugin, it has its own JVM. The two of these must add up to a bit less than 4GB.
          JAVA_TOOL_OPTIONS: -Xmx512m
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific licenses file checksum
            # when this file is changed, this key will fail
            - dockstore-support-java-{{ checksum "pom.xml" }}
            # Find the most recent cache used from any branch
            - dockstore-support-java-
      - install-git-secrets
      - run:
          name: build-all
          command: ./mvnw -B clean install -DskipTests
      - run:
          name: clean the cache
          command: |
            rm -rf ~/.m2/repository/io/dockstore
            rm -rf ~/.m2/repository/.cache/download-maven-plugin directory
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: dockstore-support-java-{{ checksum "pom.xml" }}

        # Running scan must occur after build
      - run_git_secrets_scan
      - persist_to_workspace:
          root: .
          paths:
            - .

commands:
  setup_machine:
    steps:
      - run: # Useful for verifying default versions on machine image
          name: Java/Maven/Python versions
          command: |
            java -version
            mvn -v
            python3 -V
      - run:
          name: Docker-Compose (if present)
          command: cd $DIRECTORY && docker-compose up -d || true

  send_coverage:
    steps:
      - run:
          name: send coverage
          command: bash <(curl -s https://codecov.io/bash) -F ${DIRECTORY//-} || echo "Codecov did not collect coverage reports"

  install_dockerize:
    steps:
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

  wait_for_db:
    steps:
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

  wait_for_elastic_search:
    steps:
      - run:
          name: Wait for ES
          command: |
            wget --output-document /dev/null --waitretry=5 --tries=10 --retry-connrefused localhost:9200 || true
            wget --output-document /dev/null --waitretry=5 --tries=10 --retry-connrefused localhost:9200 || true

  run_git_secrets_scan:
    steps:
      - run:
          name: Run git-secrets scan on dockstore repository
          # Needs to be after a build so that the correct configuration is set
          # by the exec-maven plugin
          command: |
            git secrets --scan

  install-git-secrets:
    steps:
      - run:
          name: Install git-secrets
          command: |
            wget --no-verbose -O git-secrets-1.3.0.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
            tar -zxf git-secrets-1.3.0.tar.gz
            cd git-secrets-1.3.0
            sudo make install

  setup_postgres:
    steps:
      - run:
          name: setup postgres user and DB
          command: |
            psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
            psql -c 'create database webservice_test with owner = dockstore;' -U postgres
            psql -c "ALTER USER dockstore WITH superuser;" -U postgres

  install_postgres_sql_client:
    steps:
      - run:
          name: Install postgresql client
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt update
            sudo apt install -y postgresql-client 

  get_workspace_and_dependencies:
    steps:
      - attach_workspace:
          at: .

  setup_for_tests:
    steps:
      - install-git-secrets
      - install_dockerize

  setup_for_postgres:
    steps:
      - install_postgres_sql_client
      - setup_postgres
      - wait_for_db

  run_tests:
    steps:
      - run:
          name: run tests
          command: |
            cd $DIRECTORY && ../mvnw -B org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate clean install -DskipITs=false -ntp | grep  -v "^Running Changeset:"
  save_test_results:
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/.*-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
