version: '2'


services:
  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - db_data:/var/lib/postgresql

  webservice: 
    build:
      context: webservice
      dockerfile: Dockerfile
      args:
        dockstore_version: 1.1
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - postgres
    volumes:
      - log_volume:/dockstore_logs

  ui:
    build:
      context: ui 
      dockerfile: Dockerfile
      args:
        dockstore_version: 1.1.1
    restart: always
    ports:
      - "80:80"
    links:
      - webservice
    volumes:
      - log_volume:/dockstore_logs

  client:
    build:
      context: client 
      dockerfile: Dockerfile
      args:
        dockstore_version: 1.1
    links:
      - webservice 
    volumes:
      - log_volume:/dockstore_logs
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    
volumes:
  log_volume: 
  db_data:
