package io.dockstore.utils.ai;

import java.util.List;

public interface AIModel {

    /**
     * Submits a prompt to the AI model and returns the response along with usage metadata.
     * @param prompt the text prompt to send to the model
     * @param temperature controls randomness of the response; higher values produce more varied output
     * @param maxResponseTokens the maximum number of tokens to generate in the response
     * @return an {@link AIResponseInfo} containing the response text, truncation status, token counts, cost, and stop reason
     */
    AIResponseInfo submitPrompt(String prompt, double temperature, int maxResponseTokens);

    /**
     * Returns the name of this AI model.
     * @return the model name
     */
    String getModelName();

    /**
     * Returns the cost per input token in USD.
     * @return price per input token
     */
    double getPricePerInputToken();

    /**
     * Returns the cost per output token in USD.
     * @return price per output token
     */
    double getPricePerOutputToken();

    /**
     * Returns the maximum number of tokens this model can process in a single context window,
     * including both input and output tokens.
     * @return the maximum context length in tokens
     */
    int getMaxContextLength();

    /**
     * Calculates the total cost in USD for a request given the number of input and output tokens consumed.
     * @param inputTokens the number of input tokens used
     * @param outputTokens the number of output tokens generated
     * @return the total cost in USD
     */
    default double calculatePrice(long inputTokens, long outputTokens) {
        return (inputTokens * getPricePerInputToken()) + (outputTokens * getPricePerOutputToken());
    }

    /**
     * Estimates the number of tokens in the given text.
     * @param prompt the text to estimate token count for
     * @return the estimated number of tokens
     */
    default int estimateTokens(String prompt) {
        // AWS Bedrock suggests using 6 characters per token as an estimation
        // https://docs.aws.amazon.com/bedrock/latest/userguide/model-customization-prepare.html
        final int estimatedCharactersPerToken = 6;
        return prompt.length() / estimatedCharactersPerToken;
    }

    /**
     * Holds the result of an AI model invocation.
     * @param aiResponse the text generated by the model
     * @param isTruncated whether the response was cut off due to the token limit
     * @param inputTokens the number of input tokens consumed
     * @param outputTokens the number of output tokens generated
     * @param cost the total cost in USD for this request
     * @param stopReason the reason the model stopped generating (e.g., "end_turn", "max_tokens")
     */
    record AIResponseInfo(String aiResponse, boolean isTruncated, long inputTokens, long outputTokens, double cost, String stopReason) {
    }

    record Message(String text, boolean cacheable) {
        static final class Builder {
            private String text;
            private boolean cacheable;

            public Builder text(String text) {
                this.text = text;
                return this;
            }

            public Builder cacheable(boolean cacheable) {
                this.cacheable = cacheable;
                return this;
            }

            public Message build() {
                return new Message(text, cacheable);
            }
        }
    }

    record Prompt(List<Message> systemMessages, List<Message> userMessages, double temperature, int maxResponseTokens) {
        static final class Builder {
            private List<Message> systemMessages;
            private List<Message> userMessages;
            private double temperature;
            private int maxResponseTokens;

            public Builder systemMessages(List<Message> systemMessages) {
                this.systemMessages = systemMessages;
                return this;
            }

            public Builder userMessages(List<Message> userMessages) {
                this.userMessages = userMessages;
                return this;
            }

            public Builder temperature(double temperature) {
                this.temperature = temperature;
                return this;
            }

            public Builder maxResponseTokens(int maxResponseTokens) {
                this.maxResponseTokens = maxResponseTokens;
                return this;
            }

            public Prompt build() {
                return new Prompt(systemMessages, userMessages, temperature, maxResponseTokens);
            }
        }
    }
}
