package io.dockstore.utils.ai;

import java.util.ArrayList;
import java.util.List;

public interface AIModel {

    /**
     * Submits a prompt to the AI model and returns the response along with usage metadata.
     * @param prompt the {@link Prompt} to send to the model
     * @return an {@link Response} containing the response text, truncation status, token counts, cost, and stop reason
     */
    Response submitPrompt(Prompt prompt);

    /**
     * Returns the name of this AI model.
     * @return the model name
     */
    String getModelName();

    /**
     * Returns the cost per input token in USD.
     * @return price per input token
     */
    double getPricePerInputToken();

    /**
     * Returns the cost per output token in USD.
     * @return price per output token
     */
    double getPricePerOutputToken();

    /**
     * Returns the maximum number of tokens this model can process in a single context window,
     * including both input and output tokens.
     * @return the maximum context length in tokens
     */
    int getMaxContextLength();

    /**
     * Approximates the total cost in USD for a request.
     * @param inputTokens the total number of input tokens used
     * @param outputTokens the number of output tokens generated
     * @return the approximate total cost in USD
     */
    default double calculatePrice(long inputTokens, long outputTokens) {
        return (inputTokens * getPricePerInputToken()) + (outputTokens * getPricePerOutputToken());
    }

    /**
     * Estimates the number of tokens in the given text.
     * @param prompt the text to estimate token count for
     * @return the estimated number of tokens
     */
    default int estimateTokens(String prompt) {
        // AWS Bedrock suggests using 6 characters per token as an estimation
        // https://docs.aws.amazon.com/bedrock/latest/userguide/model-customization-prepare.html
        final int estimatedCharactersPerToken = 6;
        return prompt.length() / estimatedCharactersPerToken;
    }

    /**
     * Holds the result of an AI model invocation.
     * @param text the text generated by the model
     * @param isTruncated whether the response was cut off due to the token limit
     * @param inputTokens the total number of input tokens consumed
     * @param outputTokens the number of output tokens generated
     * @param cost the total cost in USD for this request
     * @param stopReason the reason the model stopped generating (e.g., "end_turn", "max_tokens")
     */
    record Response(String text, boolean isTruncated, long inputTokens, long outputTokens, double cost, String stopReason) {
    }

    record Prompt(List<Prompt.Content> systemContent, List<Prompt.Content> userContent, double temperature, int outputTokens) {

        public static Builder builder() {
            return new Builder();
        }

        @SuppressWarnings("checkstyle:HiddenField")
        public static final class Builder {
            private static final int DEFAULT_OUTPUT_TOKENS = 100;
            private enum Mode { USER, SYSTEM }

            private List<Content> systemContent = new ArrayList<>();
            private List<Content> userContent = new ArrayList<>();
            private double temperature = 0.0;
            private int outputTokens = DEFAULT_OUTPUT_TOKENS;
            private Mode mode = Mode.USER;

            public Builder user() {
                mode = Mode.USER;
                return this;
            }

            public Builder system() {
                mode = Mode.SYSTEM;
                return this;
            }

            private List<Content> currentContent() {
                return mode == Mode.SYSTEM ? systemContent : userContent;
            }

            public Builder text(String text) {
                currentContent().add(new Text(text));
                return this;
            }

            public Builder cache() {
                currentContent().add(new CacheMarker());
                return this;
            }

            public Builder temperature(double temperature) {
                this.temperature = temperature;
                return this;
            }

            public Builder outputTokens(int outputTokens) {
                this.outputTokens = outputTokens;
                return this;
            }

            public Prompt build() {
                return new Prompt(systemContent, userContent, temperature, outputTokens);
            }
        }

        public interface Content {
        }

        public interface Textable {
            String toText();
        }

        record Text(String text) implements Content, Textable {
            @Override
            public String toText() {
                return text;
            }
        }

        record CacheMarker() implements Content {
        }
    }
}
