package io.dockstore.categorizer.client.cli;

import com.beust.jcommander.Parameter;
import com.beust.jcommander.Parameters;
import io.dockstore.utils.ai.AIModelType;
import io.dockstore.utils.ai.AIModelTypeConverter;
import io.dockstore.utils.ai.ClaudeModelType;
import java.io.File;
import java.util.List;

public class CategorizerCommandLineArgs {
    public static final String DEFAULT_CONFIG_FILE_NAME = "categorizer.config";

    @Parameter(names = "--help", description = "Prints help for categorizer", help = true)
    private boolean help = false;

    @Parameter(names = {"-c", "--config"}, description = "The config file path.")
    private File config = new File("./" + DEFAULT_CONFIG_FILE_NAME);

    public boolean isHelp() {
        return help;
    }

    public File getConfig() {
        return config;
    }

    @Parameters(commandNames = { "categorize-entries" }, commandDescription = "Categorize public Dockstore entries into ontology categories using AI. Use the populate-categories command to upload these categories to Dockstore.")
    public static class CategorizeEntriesCommand {

        @Parameter(names = {"-e", "--entries"}, description = "Optional file path to the CSV file containing the TRS ID and version name of the entries to categorize. The first line of the file should contain the CSV fields: trsId,version")
        private String entriesCsvFilePath;

        @Parameter(names = {"-o", "--ontology"}, required = true, description = "List of paths to ontology JSON files")
        private List<String> ontologyJsonPaths;

        @Parameter(names = {"-a", "--ai"}, description = "The AI model to use", converter = AIModelTypeConverter.class)
        private AIModelType aiModel = ClaudeModelType.CLAUDE_4_5_HAIKU;

        @SuppressWarnings("checkstyle:MagicNumber")
        @Parameter(names = {"--threadCount"}, description = "The number of threads to use for categorization")
        private int threadCount = 16;

        public String getEntriesCsvFilePath() {
            return entriesCsvFilePath;
        }

        public List<String> getOntologyJsonPaths() {
            return ontologyJsonPaths;
        }

        public AIModelType getAiModel() {
            return aiModel;
        }

        public int getThreadCount() {
            return threadCount;
        }

    }

    @Parameters(commandNames = { "list-all-entries" }, commandDescription = "List all published entries on Dockstore.")
    public static class ListAllEntriesCommand {

        @Parameter(names = {"-m", "--max"}, description = "The maximum number of entries to retrieve.")
        private int max = Integer.MAX_VALUE;

        public int getMax() {
            return max;
        }
    }

    @Parameters(commandNames = { "list-stale-entries" }, commandDescription = "List the published entries on Dockstore that are new and uncategorized, or that have changed and have not been recategorized for longer than the specified interval.")
    public static class ListStaleEntriesCommand {

        @SuppressWarnings("checkstyle:MagicNumber")
        @Parameter(names = {"-i", "--intervalSeconds"}, description = "Interval in seconds; entries last categorized at least this many seconds ago are eligible for re-categorization if changed")
        private long intervalSeconds = 3600 * 24 * 30; // seconds/hour * hours/day * 30 days

        @Parameter(names = {"-m", "--max"}, description = "The maximum number of entries to retrieve.")
        private int max = Integer.MAX_VALUE;

        public long getIntervalSeconds() {
            return intervalSeconds;
        }

        public int getMax() {
            return max;
        }
    }

    @Parameters(commandNames = { "populate-categories" }, commandDescription = "Adjust the membership of AI-managed categories on Dockstore, by adding and removing published entries, using the results generated by the categorize-entries command.")
    public static class PopulateCategoriesCommand {
        @Parameter(names = {"--categorizations"}, required = true, description = "Path to a CSV file containing the TRS ID and version of each entry, the ID of the AI-managed category, and whether the entry should be added or removed.")
        private String categorizationsCsvPath;

        public String getCategorizationsCsvPath() {
            return categorizationsCsvPath;
        }
    }

    @Parameters(commandNames = { "create-categories" }, commandDescription = "Create a set of AI-managed categories on Dockstore that corresponds to the specified ontology files.")
    public static class CreateCategoriesCommand {

        @Parameter(names = {"-o", "--ontology"}, required = true, description = "List of paths to ontology JSON files.  An AI-managed Dockstore category will be created for each \"recommended for annotation\" ontology node.")
        private List<String> ontologyJsonPaths;

        public List<String> getOntologyJsonPaths() {
            return ontologyJsonPaths;
        }
    }

    @Parameters(commandNames = { "list-categories" }, commandDescription = "List the IDs of AI-managed categories on Dockstore.  If ontologies are specified, only list the IDs of the categories that correspond to the ontologies.")
    public static class ListCategoriesCommand {

        @Parameter(names = {"-o", "--ontology"}, description = "Optional list of paths to ontology JSON files; if specified, only category IDs present in the ontologies are listed")
        private List<String> ontologyJsonPaths;

        public List<String> getOntologyJsonPaths() {
            return ontologyJsonPaths;
        }

    }

    @Parameters(commandNames = { "delete-categories" }, commandDescription = "Delete the specified list of AI-managed categories from Dockstore.")
    public static class DeleteCategoriesCommand {

        @Parameter(names = {"--categories"}, required = true, description = "Path to a CSV file containing the IDs of the categories to delete, typically produced by the list-categories command")
        private String categoriesCsvPath;

        public String getCategoriesCsvPath() {
            return categoriesCsvPath;
        }
    }

    @Parameters(commandNames = { "reindex-entries" }, commandDescription = "Trigger a reindex of all published entries on Dockstore.")
    public static class ReindexEntriesCommand {
    }
}
