package io.dockstore.categorizer.client.cli;

import com.beust.jcommander.Parameter;
import com.beust.jcommander.Parameters;
import io.dockstore.utils.ai.AIModelType;
import java.io.File;
import java.util.List;

public class CategorizerCommandLineArgs {
    public static final String DEFAULT_CONFIG_FILE_NAME = "categorizer.config";

    @Parameter(names = "--help", description = "Prints help for categorizer", help = true)
    private boolean help = false;

    @Parameter(names = {"-c", "--config"}, description = "The config file path.")
    private File config = new File("./" + DEFAULT_CONFIG_FILE_NAME);

    public boolean isHelp() {
        return help;
    }

    public File getConfig() {
        return config;
    }

    @Parameters(commandNames = { "categorize-entries" }, commandDescription = "Categorize public Dockstore entries into ontology categories using AI. Use the populate-categories command to upload these categories to Dockstore.")
    public static class CategorizeEntriesCommand {

        @Parameter(names = {"-e", "--entries"}, description = "Optional file path to the CSV file containing the TRS ID and version name of the entries to categorize. The first line of the file should contain the CSV fields: trsId,version")
        private String entriesCsvFilePath;

        @Parameter(names = {"-o", "--ontology"}, required = true, description = "List of paths to ontology JSON files")
        private List<String> ontologyJsonPaths;

        @Parameter(names = {"-a", "--ai"}, description = "The AI model to use")
        private AIModelType aiModel = AIModelType.CLAUDE_4_5_HAIKU;

        @Parameter(names = {"-d", "--dryRun"}, description = "Write the public Dockstore entries that are categorization candidates to a file")
        private boolean isDryRun = false;

        @Parameter(names = {"-m", "--max"}, description = "The max number of entries to process. If specified, the value must be greater than 0")
        private Integer max;

        public String getEntriesCsvFilePath() {
            return entriesCsvFilePath;
        }

        public List<String> getOntologyJsonPaths() {
            return ontologyJsonPaths;
        }

        public AIModelType getAiModel() {
            return aiModel;
        }

        public boolean isDryRun() {
            return isDryRun;
        }

        public Integer getMax() {
            return max;
        }

        /**
         * Headers for the input data file of entries to categorize.
         */
        public enum InputCsvHeaders {
            trsId, version
        }

        /**
         * Headers for the output file containing the AI-generated categories.
         */
        public enum OutputCsvHeaders {
            trsId,
            version,
            descriptorUrl, // Raw GitHub URL of the descriptor file used to generate the categories
            descriptorChecksum, // Checksum of the descriptor file used to generate the categories. Can be used to determine if the content has changed
            isTruncated, // Whether the descriptor file content was truncated because it exceeded the token maximum
            promptTokens, // Number of tokens in prompt
            completionTokens, // Number of tokens in response
            cost, // Estimated cost of the prompt and completion tokens
            finishReason, // The reason that the response stopped
            categories // AI-suggested ontology categories (JSON array)
        }

        /**
         * Headers for entries that failed to have categories generated.
         */
        public enum ErrorsCsvHeaders {
            trsId,
            version,
            errorMessage
        }
    }

    @Parameters(commandNames = { "list-stale-entries" }, commandDescription = "List public Dockstore entries that are new and uncategorized, or that have changed since last categorization.")
    public static class ListStaleEntriesCommand {

        @Parameter(names = {"-i", "--intervalSeconds"}, required = true, description = "Interval in seconds; entries last categorized at least this many seconds ago are eligible for re-categorization if changed")
        private Long intervalSeconds;

        @Parameter(names = {"-m", "--max"}, description = "The max number of entries to retrieve. If specified, the value must be greater than 0")
        private Integer max;

        public Long getIntervalSeconds() {
            return intervalSeconds;
        }

        public Integer getMax() {
            return max;
        }
    }

    @Parameters(commandNames = { "populate-categories" }, commandDescription = "Upload AI-generated ontology categories, generated by the categorize-entries command, for public Dockstore entries.")
    public static class PopulateCategoriesCommand {
        @Parameter(names = {"-cat", "--categories"}, required = true, description = "The file path to the CSV file containing the TRS ID and AI-generated categories of the entries to upload. The first line of the file should contain the CSV fields output by the categorize-entries command. Path may be a local path or an S3 URI.")
        private String categoriesCsvFilePath;

        @Parameter(names = {"-r", "--review"}, description = "Whether manual review should be performed before uploading. If specified, the program will display each category suggestion and ask the user if it should be uploaded")
        private boolean review = false;

        public String getCategoriesCsvFilePath() {
            return categoriesCsvFilePath;
        }

        public boolean isReview() {
            return review;
        }
    }
}
