package io.dockstore.categorizer.client.cli;

import com.beust.jcommander.Parameter;
import com.beust.jcommander.Parameters;
import io.dockstore.utils.ai.AIModelType;
import java.io.File;
import java.util.List;

public class CategorizerCommandLineArgs {
    public static final String DEFAULT_CONFIG_FILE_NAME = "categorizer.config";

    @Parameter(names = "--help", description = "Prints help for categorizer", help = true)
    private boolean help = false;

    @Parameter(names = {"-c", "--config"}, description = "The config file path.")
    private File config = new File("./" + DEFAULT_CONFIG_FILE_NAME);

    public boolean isHelp() {
        return help;
    }

    public File getConfig() {
        return config;
    }

    @Parameters(commandNames = { "categorize-entries" }, commandDescription = "Categorize public Dockstore entries into ontology categories using AI. Use the populate-categories command to upload these categories to Dockstore.")
    public static class CategorizeEntriesCommand {

        @Parameter(names = {"-e", "--entries"}, description = "Optional file path to the CSV file containing the TRS ID and version name of the entries to categorize. The first line of the file should contain the CSV fields: trsId,version")
        private String entriesCsvFilePath;

        @Parameter(names = {"-o", "--ontology"}, required = true, description = "List of paths to ontology JSON files")
        private List<String> ontologyJsonPaths;

        @Parameter(names = {"-a", "--ai"}, description = "The AI model to use")
        private AIModelType aiModel = AIModelType.CLAUDE_4_5_HAIKU;

        public String getEntriesCsvFilePath() {
            return entriesCsvFilePath;
        }

        public List<String> getOntologyJsonPaths() {
            return ontologyJsonPaths;
        }

        public AIModelType getAiModel() {
            return aiModel;
        }

        /**
         * Headers for the input data file of entries to categorize.
         */
        public enum EntryCsvHeaders {
            trsId, version
        }

        /**
         * Headers for the output file containing the AI-generated categories.
         */
        public enum CategorizationCsvHeaders {
            trsId,
            version,
            categoryId,
            isMember
            /**
             * TODO: Add back some diagnostic output?
             */
        }

        /**
         * Headers for entries that failed to have categories generated.
         */
        public enum ErrorsCsvHeaders {
            trsId,
            version,
            errorMessage
        }
    }

    @Parameters(commandNames = { "list-all-entries" }, commandDescription = "List all public Dockstore entries.")
    public static class ListAllEntriesCommand {

        @Parameter(names = {"-m", "--max"}, description = "The max number of entries to retrieve. If specified, the value must be greater than 0")
        private int max = Integer.MAX_VALUE;

        public int getMax() {
            return max;
        }
    }

    @Parameters(commandNames = { "list-stale-entries" }, commandDescription = "List public Dockstore entries that are new and uncategorized, or that have changed since last categorization.")
    public static class ListStaleEntriesCommand {

        @SuppressWarnings("checkstyle:MagicNumber")
        @Parameter(names = {"-i", "--intervalSeconds"}, description = "Interval in seconds; entries last categorized at least this many seconds ago are eligible for re-categorization if changed")
        private long intervalSeconds = 3600 * 24 * 30; // seconds/hour * hours/day * days

        @Parameter(names = {"-m", "--max"}, description = "The max number of entries to retrieve. If specified, the value must be greater than 0")
        private int max = Integer.MAX_VALUE;

        public long getIntervalSeconds() {
            return intervalSeconds;
        }

        public int getMax() {
            return max;
        }
    }

    @Parameters(commandNames = { "populate-categories" }, commandDescription = "Upload AI-generated ontology categories, generated by the categorize-entries command, for public Dockstore entries.")
    public static class PopulateCategoriesCommand {
        @Parameter(names = {"--categorizations"}, required = true, description = "The file path to the CSV file containing the TRS ID and AI-generated categories of the entries to upload. Path may be a local path or an S3 URI.")
        private String categorizationsCsvPath;

        public String getCategorizationsCsvPath() {
            return categorizationsCsvPath;
        }
    }

    @Parameters(commandNames = { "create-categories" }, commandDescription = "Create categories in Dockstore corresponding to entries in the specified ontology files.")
    public static class CreateCategoriesCommand {

        @Parameter(names = {"-o", "--ontology"}, required = true, description = "List of paths to ontology JSON files whose entries will be created as categories")
        private List<String> ontologyJsonPaths;

        public List<String> getOntologyJsonPaths() {
            return ontologyJsonPaths;
        }
    }

    @Parameters(commandNames = { "delete-categories" }, commandDescription = "Delete categories from Dockstore whose IDs match a regular expression.")
    public static class DeleteCategoriesCommand {

        @Parameter(names = {"-r", "--regexp"}, required = true, description = "Regular expression matched against category IDs; matching categories are deleted")
        private String categoryIdRegexp;

        public String getCategoryIdRegexp() {
            return categoryIdRegexp;
        }
    }
}
