- name: Jenkins slave requirements
  hosts: localhost
  connection: localhost
  tasks:
    - name: Install JDK
      become: yes
      apt:
        name: openjdk-8-jdk
    - name: Install python-pip
      become: yes
      apt:
        name: python-pip
    - name: Install https
      become: yes
      apt:
        name: apt-transport-https
    - name: Add docker repository and update apt cache
      become: yes
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ansible_distribution | lower }} {{ansible_distribution_release}} stable"
        update_cache: yes
        state: present
    - name: Install docker
      become: yes
      apt:
        update_cache: yes
        name: docker-ce
        allow_unauthenticated: yes
    - name: Install cwl pip deps
      become: yes
      pip:
        requirements: https://raw.githubusercontent.com/ga4gh/dockstore/f01f4a357a353b60ac2348c51fedd63966b759a1/dockstore-webservice/src/main/resources/requirements/1.6.0/requirements.txt
    - name: Install aws cli
      become: yes
      pip:
        name: awscli
        version: 1.11.170
    - name: Download Dockstore
      become: yes
      get_url:
        url: https://github.com/ga4gh/dockstore/releases/download/{{version}}/dockstore
        dest: /usr/local/bin
        mode: a+rwx
    - name: echo $HOME
      become: yes
      become_user: jenkins
      shell: "echo $HOME"
      register: jenkins_home
    - name: Create directory if it doesn't exist
      become: yes
      become_user: jenkins
      file:
        path: "{{jenkins_home.stdout}}/.dockstore"
        state: directory
    - name: Install s3cmd
      become: yes
      apt:
        name: s3cmd
