- name: Jenkins slave requirements
  hosts: localhost
  connection: localhost
  tasks:
    - name: Install JDK
      become: yes
      apt:
        name: openjdk-11-jdk
    - name: Install python-pip
      become: yes
      apt:
        name: python3-pip
    - name: Install https
      become: yes
      apt:
        name: apt-transport-https
    - name: Install cwl pip deps
      become: yes
      pip:
        requirements: https://dev.dockstore.net/api/metadata/runner_dependencies?client_version=1.10.0&python_version=3&runner=cwltool&output=text
        executable: pip3
    - name: Install aws cli
      become: yes
      pip:
        name: awscli
        version: 1.11.170
        executable: pip3
    - name: Download Dockstore
      become: yes
      get_url:
        url: https://github.com/dockstore/dockstore-cli/releases/download/{{version}}/dockstore
        dest: /usr/local/bin
        mode: a+rwx
    - name: echo $HOME
      become: yes
      become_user: jenkins
      shell: "echo $HOME"
      register: jenkins_home
    - name: Create directory if it doesn't exist
      become: yes
      become_user: jenkins
      file:
        path: "{{jenkins_home.stdout}}/.dockstore"
        state: directory
    - name: Install s3cmd
      become: yes
      apt:
        name: s3cmd
