- name: Jenkins slave requirements
  hosts: localhost
  connection: localhost
  tasks:
    - name: Add jenkins user
      become: yes
      user:
        name: jenkins
        shell: /bin/bash
        groups: docker, sudo
        append: yes
    - name: Install https
      become: yes
      apt:
        name: apt-transport-https
    - name: Add docker repository and update apt cache
      become: yes
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ansible_distribution | lower }} {{ansible_distribution_release}} stable"
        update_cache: yes
        state: present
    - name: Install docker
      become: yes
      apt:
        update_cache: yes
        name: docker-ce
        allow_unauthenticated: yes
