- name: Jenkins slave requirements
  hosts: local
  connection: local
  tasks:
<<<<<<< HEAD
    - name: Install JDK
      become: yes
      apt:
        name: default-jre
    - name: Install python-pip
      become: yes
      apt:
        name: python-pip
    - name: Install https
      become: yes
      apt:
        name: apt-transport-https
    - name: Add docker repository and update apt cache
      become: yes
      apt_repository:
        repo: "deb https://apt.dockerproject.org/repo {{ansible_distribution | lower }}-{{ansible_distribution_release}} main"
        update_cache: yes
        state: present
=======
>>>>>>> d7e8c79... Feature/jenkins example (#5)
    - name: Install docker
      become: yes
      apt:
        name: docker-engine
<<<<<<< HEAD
        allow_unauthenticated: yes
=======
>>>>>>> d7e8c79... Feature/jenkins example (#5)
    - name: Install setuptools
      become: yes
      pip:
        name: setuptools
        version: 24.0.3
<<<<<<< HEAD
=======
    - name: Install cwltool
      become: yes
      pip:
        name: cwltool
        version: 1.0.20161114152756
>>>>>>> d7e8c79... Feature/jenkins example (#5)
    - name: Install schema-salad
      become: yes
      pip:
        name: schema-salad
        version: 1.18.20161005190847
    - name: Install avro
      become: yes
      pip:
        name: avro
        version: 1.8.1
<<<<<<< HEAD
    - name: Install cwltool
      become: yes
      pip:
        name: cwltool
        version: 1.0.20161114152756
=======
>>>>>>> d7e8c79... Feature/jenkins example (#5)
    - name: Download Dockstore
      become: yes
      get_url:
        url: https://github.com/ga4gh/dockstore/releases/download/1.1.2/dockstore
        dest: /usr/local/bin
        mode: a+rwx
<<<<<<< HEAD
<<<<<<< HEAD
=======
    - name: echo $HOME
      become: yes
      become_user: jenkins
      shell: "echo $HOME"
      register: jenkins_home
>>>>>>> 8353215... Pretty print reports and added documentation
    - name: Create directory if it doesn't exist
      become: yes
      become_user: jenkins
      file:
        path: "{{jenkins_home.stdout}}/.dockstore"
        state: directory
=======
>>>>>>> d7e8c79... Feature/jenkins example (#5)
    - name: Write dockstore config file
      become: yes
      become_user: jenkins
      copy:
        content: "token: test \nserver-url: https://dockstore.org:8443"
        dest: "{{jenkins_home.stdout}}/.dockstore/config"
        mode: 0555

