- name: Jenkins slave requirements
  hosts: localhost
  connection: localhost
  tasks:
    - name: Install JDK
      become: yes
      apt:
        name: openjdk-11-jdk
    - name: Install https
      become: yes
      apt:
        name: apt-transport-https
    - name: Add an apt key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository and update apt cache
      become: yes
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ansible_distribution | lower }} {{ansible_distribution_release}} stable"
        update_cache: yes
        state: present
    - name: Install docker
      become: yes
      apt:
        update_cache: yes
        name: docker-ce
        allow_unauthenticated: yes
    - name: Install python-pip
      become: yes
      apt:
        name: python3-pip
    - name: Install aws cli
      become: yes
      pip:
        name: awscli
        version: 1.11.170
        executable: pip3
    - name: Add jenkins user
      become: yes
      user:
        name: jenkins
        shell: /bin/bash
        groups: docker, sudo
        append: yes
    - name: Create /mnt/output directory
      file:
        path: /mnt/output
        state: directory
        mode: '0777'
    - name: Set authorized keys taken from url
      become: yes
      authorized_key:
        user: jenkins
        state: present
        key: https://raw.githubusercontent.com/ga4gh/dockstore-support/feature/playbook/tooltester/src/main/resources/id_rsa.pub
