name: Tagged release deploy

on:
  workflow_dispatch:

jobs:
  call-reusable-tagged-release:
    uses: dockstore/workflow-actions/.github/workflows/deploy_tagged.yaml@seab-6771/reusable-image-deploy
    secrets: inherit

  deploy_image:
    uses: dockstore/workflow-actions/.github/workflows/deploy_image.yaml@seab-6771/reusable-image-deploy
    with:
      quayRepository: dockstore-support
    secrets: inherit
